// leave off @2x/@3x
const images = {
  logo1: require('../Images/logo-1.png'),
  logo2: require('../Images/logo-2.png'),
  logo3: require('../Images/logo-3.png'),
  videoOnboarding: require('../Images/onboarding.mp4'),
  play: require('../Images/play.png'),
  pause: require('../Images/pause.png'),
  location: require('../Images/location-filled.png'),
  add1: require('../Images/add_medium.png'),
  search: require('../Images/search.png'),
  crossBold: require('../Images/cross_bold.png'),
  crossMedium: require('../Images/cross_medium.png'),
  view: require('../Images/view.png'),
  arrow_left: require('../Images/arrow_medium_left.png'),
  packageFilled: require('../Images/package_filled.png'),
  packageMed: require('../Images/package_med.png'),
  cartFilled: require('../Images/cart_filled.png'),
  cartMed: require('../Images/cart_med.png'),
  likeFilled: require('../Images/like_filled.png'),
  likeMed: require('../Images/like_med.png'),
  dots: require('../Images/dots_med.png'),
  locationMed: require('../Images/location_medium.png'),
  sortRows: require('../Images/sort-rows.png'),
  sortSquares: require('../Images/sort-squares.png'),
  starFilled: require('../Images/star_filled.png'),
  stock: require('../Images/pie-chart.png'),
  share: require('../Images/connect_medium.png'),
  info1: require('../Images/info_01.png'),
  info2: require('../Images/info_02.png'),
  verification: require('../Images/verification.png'),
  userDocImage:require('../Images/usercenter/Document.png'),
  userIconImage:require('../Images/usercenter/Icon.png'),
  userLogoImage:require('../Images/usercenter/Logo.png'),
  userMediumImage:require('../Images/usercenter/Medium.png'),
  userSettingImage:require('../Images/usercenter/setting.png'),
  userStarImage:require('../Images/usercenter/star.png'),
}

export default images
