export const Address = {
  name: "Address",
  primaryKey: "id",
  properties: {
    id: { type: "string?", default: null },
    flat: { type: "string?", default: null },
    floor: { type: "string?", default: null },
    block: { type: "string?", default: null },
    building: { type: "string?", default: null },
    houseNumber: { type: "string?", default: null },
    streetAddress1: { type: "string?", default: null },
    streetAddress2: { type: "string?", default: null },
    townCity: { type: "string?", default: null },
    villageArea: { type: "string?", default: null },
    district: { type: "string?", default: null },
    provinceState: { type: "string?", default: null },
    country: { type: "string?", default: null },
    areaCode: { type: "string?", default: null },
    landMark: { type: "string?", default: null },
    pinCode: { type: "string?", default: null },
    addressType: { type: "string?", default: null },
    referenceId: { type: "string?", default: null },
    defaultAddress: "bool",
  },
};
