export const Address = {
  name: "Address",
  primaryKey: "id",
  properties: {
    id: "string",
    flat: "string",
    floor: "string",
    block: "string",
    building: "string",
    houseNumber: "string",
    streetAddress1: "string",
    streetAddress2: "string",
    townCity: "string",
    villageArea: "string",
    district: "string",
    provinceState: "string",
    country: "string",
    areaCode: "string",
    landMark: "string",
    pinCode: "string",
    addressType: "string",
    referenceId: "string",
    defaultAddress: "bool",
  },
};
