export const ProductSchema = {
  name: "ProductSchema",
  // primaryKey: "productId",
  properties: {
    photo: { type: "string?", default: null },
    photoUrls: { type: "string[]", default: null },
    shortName: { type: "string?", default: null },
    numberOfStars: { type: "float?", default: null },
    numberOfReviews: { type: "int?", default: null },
    retailPrice: { type: "float?", default: null },
    wholeSalePrice: { type: "float?", default: null },
    salePercentage: { type: "float?", default: null },
    percentOff: { type: "int?", default: null },
    deliveryFee: { type: "float?", default: null },
    amountSaved: { type: "float?", default: null },
    pickUpFromSeller: { type: "bool?", default: null },
    openUntil: { type: "string?", default: null },
    noOfOrderedItems: { type: "int?", default: null },
    noOfItemsInStock: { type: "int?", default: null },
    description: { type: "string?", default: null },
    technicalDetails: { type: "string?", default: null },
    highlightBullets: { type: "string[]", default: null },
    seller: { type: "SellerView?", default: null },
    returnPolicies: {
      type: "list",
      objectType: "ProductReturnPolicyView",
      default: null,
    },
    listingVariants: {
      type: "list",
      objectType: "ListingVariantView",
      default: null,
    },
    relatedProducts: { type: "string?", default: null },
    reviews: { type: "list", objectType: "ReviewView", default: null },
    listingId: { type: "string?", default: null },
    productId: { type: "string?", default: null },
    storeId: { type: "string?", default: null },
    storeName: { type: "string?", default: null },
    status: { type: "string?", default: null },
    rating: { type: "int?", default: null },
    closedDate: { type: "string?", default: null },
    deliveryDate: { type: "string?", default: null },
    productListingType: { type: "string?", default: null },
    shippingMethodsAvailable: { type: "string?", default: null },
    progressBarValue: { type: "int?", default: null },
    numberOfItemsAvailable: { type: "int?", default: null },
    minQuantityPerCart: { type: "int?", default: null },
    maxQuantityPerCart: { type: "int?", default: null },
    qtyAvailable: { type: "int?", default: null },
    minSoldQuantity: { type: "int?", default: null },
    minQtyPerCart: { type: "int?", default: null },
    itemSold: { type: "int?", default: null },
    createOn: { type: "string?", default: null },
    collectionPointAddressId: { type: "string?", default: null },
    collectionPoIntAddress: { type: "Address?", default: null },
    returnAddressId: { type: "string?", default: null },
    returnAddress: { type: "Address?", default: null },
    longName: { type: "string?", default: null },
    ratingDetail: { type: "RatingDetail?", default: null },
    announcementId: { type: "string?", default: null },
    sellerId: { type: "string?", default: null },
    deliveryOption: { type: "string?", default: null },
    courierShippingFee: { type: "int?", default: null },
    courierShippingFeeTax: { type: "int?", default: null },
  },
};
